name: Deploy Angular Frontend to Azure Static Web Apps (Dev & Prod)

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.3.0'

      - name: Install dependencies
        run: |
          cd frontend/devforabuck-web
          npm install

      - name: Build Angular app
        run: |
          cd frontend/devforabuck-web
          npm run build --prod

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/devforabuck-web"
          output_location: "frontend/devforabuck-web/dist/devforabuck-web/browser"
          skip_app_build: true
        if: github.ref == 'refs/heads/dev'

      - name: Deploy to Azure Static Web Apps (Prod)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/devforabuck-web"
          output_location: "frontend/devforabuck-web/dist/devforabuck-web/browser"
          skip_app_build: true
        if: github.ref == 'refs/heads/main'
