name: Deploy Angular Frontend to Azure Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '23.3.0'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          cd frontend/devforabuck-web
          npm ci

      # 4️⃣ Build Angular app
      - name: Build Angular app
        run: |
          cd frontend/devforabuck-web
          npm run build --prod

      # 5️⃣ Zip the build output to ensure clean structure
      - name: Zip build output
        run: |
          cd frontend/devforabuck-web/dist/devforabuck-web/browser
          zip -r ../../../deploy.zip .

      # 6️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      # 7️⃣ Deploy the zip to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: devforabuck-web-dev
          package: frontend/devforabuck-web/dist/deploy.zip
