name: Deploy Angular Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.3.0'

      - name: Install dependencies
        working-directory: frontend/devforabuck-web
        run: npm install

      - name: Build Angular app
        working-directory: frontend/devforabuck-web
        run: npm run build -- --configuration=production

      # Verify build output structure
      - name: Debug build output
        working-directory: frontend/devforabuck-web
        run: |
          echo "Build output structure:"
          ls -R dist
          echo "Checking for index.html:"
          ls dist/devforabuck-web/browser/index.html || echo "index.html not found!"

      # Deploy to Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/devforabuck-web/dist/devforabuck-web/browser"  # Full path to built files
          output_location: ""  # Empty because we're pointing directly to the built files
          skip_app_build: true