name: Deploy - Static Frontend

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.3.0'

      - name: Install dependencies
        working-directory: frontend/devforabuck-web
        run: npm install

      - name: Build Angular app (Dev)
        if: github.ref == 'refs/heads/dev'
        working-directory: frontend/devforabuck-web
        run: npm run build -- --configuration=development

      - name: Build Angular app (Prod)
        if: github.ref == 'refs/heads/main'
        working-directory: frontend/devforabuck-web
        run: npm run build -- --configuration=production

      # Deploy to Static Web Apps DEV (only on dev branch)
      - name: Deploy to Azure Static Web Apps - DEV
        if: github.ref == 'refs/heads/dev'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/devforabuck-web/dist/devforabuck-web/browser"
          output_location: ""
          skip_app_build: true

      # Deploy to Static Web Apps PROD (only on main branch)
      - name: Deploy to Azure Static Web Apps - PROD
        if: github.ref == 'refs/heads/main'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/devforabuck-web/dist/devforabuck-web/browser"
          output_location: ""
          skip_app_build: true