name: Deploy Angular Frontend to Azure Static Web Apps (Dev & Prod)

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.3.0'

      - name: Install dependencies
        working-directory: frontend/devforabuck-web
        run: npm install

      - name: Build Angular app (production)
        working-directory: frontend/devforabuck-web
        run: npm run build -- --configuration=production

      # Debug step to show directory structure
      - name: Debug directory structure
        working-directory: frontend/devforabuck-web
        run: ls -R dist

      # ✅ Deploy to Dev — only on dev branch
      - name: Deploy to Azure Static Web Apps (Dev)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/devforabuck-web"
          app_artifact_location: "frontend/devforabuck-web/dist/devforabuck-web" # Adjust after debug
          skip_app_build: true
        if: github.ref == 'refs/heads/dev'

      # ✅ Deploy to Prod — only on main branch
      - name: Deploy to Azure Static Web Apps (Prod)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/devforabuck-web"
          app_artifact_location: "frontend/devforabuck-web/dist/devforabuck-web" # Adjust after debug
          skip_app_build: true
        if: github.ref == 'refs/heads/main'